services:
  front:
    image: horaziy/atomic-hack-frontend:latest
    ports:
      - 3000:3000
    networks:
    - atomic
    restart: unless-stopped

  back:
    image: horaziy/atomic-hack-backend:latest
    ports:
      - 8080:8080
    networks:
      - atomic
    restart: unless-stopped

  nginx:
    image: nginx:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - atomic

networks:
  atomic:
    