services:
  # backend:
  #   image: backend:test
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_URL=postgresql+asyncpg://postgres:password@db:5432/postgres
  #   ports:
  #     - 43000:8080
  #   depends_on:
  #     - db
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432


